<html>
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>Анализатор страниц</title>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
    </head>

    <body class="min-vh-100 d-flex flex-column">
        <header class="flex-shrink-0">
            <nav class="navbar navbar-expand-md navbar-dark bg-dark px-3">
                <a class="navbar-brand" href="/">Анализатор страниц</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
                        aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarNav">
                    <ul class="navbar-nav">
                        <li class="nav-item">
                            <a class="nav-link active" href="/">Главная</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link" href="/urls">Сайты</a>
                        </li>

                    </ul>
                </div>
            </nav>
        </header>

        <main class="flex-grow-1">
            <div class="container-lg mt-3">
                <h1></h1>
                <div class="row">
                    <div class="col-12 col-md-10 col-lg-8 mx-auto border rounded-3 bg-light p-5">
                        <h1 class="display-3">Анализатор страниц</h1>
                        <p class="lead">Проверьте сайт на SEO пригодность</p>
                        <form action="/urls" method="post" class="row" required>
                            <div class="col-8">
                                <input
                                        type="text"
                                        name="url[name]"
                                        value="<?= htmlspecialchars($url['name'] ?? ''); ?>"
                                        class="form-control form-control-lg <?php if (isset($errors)) : ?> is-invalid"<?php endif ?>
                                        placeholder="https://www.example.com"
                                >
                                <?php if (isset($errors)) : ?>
                                    <div class="invalid-feedback">Неправильный URL</div>
                                <?php endif ?>
                            </div>
                            <div class="col-2">
                                <input type="submit" class="btn btn-primary btn-lg ms-0 px-5 mx-3" value="Проверить">
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </main>
        <footer class="border-top py-3 mt-5 flex-shrink-0"></footer>
    </body>
</html>